file_path:
   qaqc_data_directory: /Users/quinn/workfiles/Research/SSC_forecasting/run_flare_package/flarer_aed/data_processed
   noaa_directory: /Users/quinn/workfiles/Research/SSC_forecasting/SCC_data/
   inflow_directory: /Users/quinn/workfiles/Research/SSC_forecasting/SCC_data/
   configuration_directory: /Users/quinn/workfiles/Research/SSC_forecasting/run_flare_package/flarer_aed/configuration
   execute_directory: /Users/quinn/workfiles/Research/SSC_forecasting/run_flare_package/flarer_aed/flare_tempdir
   forecast_output_directory: /Users/quinn/workfiles/Research/SSC_forecasting/run_flare_package/flarer_aed/forecast_output
   run_config: /Users/quinn/workfiles/Research/SSC_forecasting/run_flare_package/flarer_aed/configuration/flarer/configure_run.yml
location:
   site_id: fcre
   name: Falling Creek Reservoir
   latitude: 37.307   #Degrees North
   longitude: 79.837  #Degrees West
metadata:
   generate_eml: TRUE
   forecast_project_id: test
   abstract: "This is where a longer description of the forest can be added"
   forecast_title: FLARE
   intellectualRights: insert license
   model_description:
      forecast_model_id: https://github.com/rqthomas/flare/commit/d1ddcb07b9d28863890597503fc4aa4a4496de56
      name: General Lake Model
      type: process-based
      repository: https://github.com/AquaticEcoDynamics/GLM/releases/tag/v3.1.0
   me:
      individualName:
         givenName: "Quinn"
         surName: "Thomas"
      electronicMailAddress:  "INSERT"
      id: INSERT ORCID
da_setup:
    da_method: enkf
    par_fit_method: inflate
    ensemble_size:  100
    localization_distance: .na #distance in meters were covariances in the model error are used
    no_negative_states: TRUE
    assimilate_first_step: FALSE
    use_obs_constraint: TRUE
model_settings:
   ncore: 6
   model_name: glm_aed #other is "null"
   base_GLM_nml: glm3.nml
   base_AED_nml: aed2.nml
   base_AED_phyto_pars_nml: aed2_phyto_pars.nml
   base_AED_zoop_pars_nml: aed2_zoop_pars.nml
   modeled_depths: [0.10, 0.33, 0.67,
                    1.00, 1.33, 1.67,
                    2.00, 2.33, 2.67,
                    3.00, 3.33, 3.67,
                    4.00, 4.33, 4.67,
                    5.00, 5.33, 5.67,
                    6.00, 6.33, 6.67,
                    7.00, 7.33, 7.67,
                    8.00, 8.33, 8.67,
                    9.00]
   par_config_file: parameter_calibration_config_aed.csv
   obs_config_file: observations_config_aed.csv
   states_config_file: states_config_aed.csv
   depth_model_sd_config_file: depth_model_sd_aed.csv
default_init:
   lake_depth: 9.4  #not a modeled state
   temp: [25.667, 24.9101, 23.067, 21.8815, 19.6658, 16.5739, 12.9292, 12.8456, 12.8127, 12.8079, 12.778]
   temp_depths: [0.127, 1.004, 2.005, 3.021, 4.002, 5.004, 6.004, 7.01, 8.001, 9.015, 9.518]
   salinity: 0.0
   snow_thickness: 0.0
   white_ice_thickness: 0.0
   blue_ice_thickness: 0.0
inflow:
   use_forecasted_inflow: FALSE
   forecast_inflow_model: FLOWS-NOAAGEFS-AR1
met:
   use_forecasted_met: FALSE
   forecast_met_model: NOAAGEFS_1hr-debias
uncertainty:
   observation: TRUE
   process: TRUE
   weather: TRUE
   initial_condition: TRUE
   parameter: TRUE
   met_downscale: TRUE
   inflow_process: TRUE
output_settings:
   diagnostics_names:  [extc_coef,
                    PHY_cyano_fI,
                    PHY_cyano_fNit,
                     PHY_cyano_fPho,
                    PHY_cyano_fT,
                     PHY_green_fI,
                    PHY_green_fNit,
                     PHY_green_fPho,
                     PHY_green_fT,
                     PHY_diatom_fI,
                     PHY_diatom_fNit,
                     PHY_diatom_fPho,
                     PHY_diatom_fT,
                     rad]
management:
   simulate_sss: TRUE
   sss_depth: 8.0
   use_specified_sss: TRUE
   specified_sss_inflow_file: .na
   specified_sss_outflow_file: .na
   forecast_sss_flow: 1000
   forecast_sss_oxy: 500
   #umol/m3  of oxygen if SSS turned on in forecast
   sss_fname: FCR_SSS_inflow_2013_2020.csv
   sss_inflow_factor: 0.25
